vim.g.mapleader = ' '
vim.g.maplocalleader = ' '
vim.o.ignorecase = true
vim.o.cursorline = true
vim.o.smartcase = true
vim.o.nu = true
vim.o.relativenumber = true
vim.o.tabstop = 4
vim.o.softtabstop = 4
vim.o.shiftwidth = 4
vim.o.expandtab = true
vim.o.smartindent = true
vim.o.autoindent = true
vim.o.smarttab = true
vim.o.wrap = false
vim.o.hlsearch = false
vim.o.incsearch = true
vim.o.termguicolors = true
vim.o.scrolloff = 10
vim.o.updatetime = 50
vim.opt.completeopt = { 'menu', 'menuone', 'noselect' }
vim.g.loaded_netrw = 1
vim.g.loaded_netrwPlugin = 1
